### PR TITLE
Feature/update readme

### LINKED ISSUE #30: Update frontend document

### PR DESCRIPTION
**Pull request by ericqiangguo**
boss zhang, xing and lv, here is the draft of frontend document. Please give me some comments.

---
edit by _xingweitian_: 
resolve #30.

### CODE REVIEW

**Comment by xingweitian** [comment]
I update the url of wiki.

**Comment by xingweitian** [comment]
The other things look good to me.

**Comment by ericqiangguo** [comment]
> The other things look good to me.

thanks boss xing

**Comment by xingweitian** [comment]
And I also modify another little things. See them in my commits and also give me some comments. Please feel free to change if there is somewhere that can be improved.

**Comment by ericqiangguo** [comment]
> And I also modify another little things. See it in my commits and also give me some comments. Please feel free to change if there is somewhere that can be improved.

cool!!!

**Comment by xingweitian** [comment]
Looks good to me.

**Review by xingweitian — APPROVED** [review]

**Comment by ericqiangguo** [comment]
> Looks good to me.

diao!diao!diao!

**Review by zhangjiangqige — APPROVED** [review]

**Pull request merged**
