### PR TITLE
Feature/test home signup

### LINKED ISSUE #33: create test for signup page and homepage

### PR DESCRIPTION
**Pull request by ericqiangguo**
Resolve #33  
create the test for home page and signup page.

### CODE REVIEW

**Comment by xingweitian** [comment]
Travis failed, please check it. @lyuboxin please give some advice.

**Comment by lyuboxin** [comment]
please add headless attribute to chrome in test_addroom.py

**Comment by xingweitian** [comment]
```
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    testLogin('unexist username', 'lyuboxin1@gmail', '', 'username or password is wrong')
  File "test.py", line 16, in testLogin
    checkresult(result)
  File "test.py", line 19, in checkresult
    resultMsg(browser.is_text_present(x))
  File "test.py", line 8, in resultMsg
    assert x == True
AssertionError
The command "bash test.sh" exited with 1.
```
@lyuboxin @ericqiangguo check this

**Comment by xingweitian** [comment]
@ericqiangguo good job! lets resolve conflict and merge at tomorrow.

**Comment by zhangjiangqige** [comment]
Are files under [/img/Home Page_files](https://github.com/new-airbnb/kitchen-towel/tree/bc49c669628624ef9627ea6e0ac1f2d3c2dfd4ea/img/Home%20Page_files) necessary?

**Comment by ericqiangguo** [comment]
> Are files under [/img/Home Page_files](https://github.com/new-airbnb/kitchen-towel/tree/bc49c669628624ef9627ea6e0ac1f2d3c2dfd4ea/img/Home%20Page_files) necessary?

sorry, it is not necessary. I will delete them later

**Comment by ericqiangguo** [comment]
> @ericqiangguo good job! lets resolve conflict and merge at tomorrow.
great!

**Review by lyuboxin — APPROVED** [review]

**Review by xingweitian — APPROVED** [review]

**Pull request merged**
