### PR TITLE
fix scollbar_and_mark_reserved

### LINKED ISSUE #63: fix bugs in addroompage and homepage
bug1: cannot upload two pictures
bug2: the house that are not booked marked red
bug3: no scroll bar in home page table

### PR DESCRIPTION
**Pull request by lyuboxin**
Resolve #63 fix
bug1: cannot upload two pictures
bug2: the house that are not booked marked red
bug3: no scroll bar in home page table

### CODE REVIEW

**Comment by xingweitian** [comment]
the default location in "add room" is still in Australia.

**Comment by xingweitian** [comment]
when in sign in page, can not jump to sign up page. please contact Qiang, maybe he has already fixed this issue.

**Review by xingweitian — CHANGES_REQUESTED** [review]
see my comments.

**Comment by xingweitian** [comment]
try to see if we can resolve the issue that when the number of photo is smaller than 3, there will be still 3 rectangles.

**Review by xingweitian — APPROVED** [review]

**Review by zhangjiangqige — APPROVED** [review]

**Pull request merged**
